export interface CategoryContent {
  title: string
  metaDesc: string
  h1: string
  intro: string
  popularPairs: { from: string; to: string; desc: string }[]
  useCases: string[]
  formula?: string
  faq: { q: string; a: string }[]
}

export const categoryContent: Record<string, CategoryContent> = {
  length: {
    title: 'Length Converter — Convert Meters, Feet, Inches, Kilometers & More',
    metaDesc: 'Free online length converter. Convert between meters, feet, inches, kilometers, miles, centimeters, and 20+ length units instantly. Natural language input supported.',
    h1: 'Length Conversion',
    intro: 'Convert between any length units instantly — from nanometers to parsecs. The length converter supports all common metric and imperial units including meters (m), kilometers (km), centimeters (cm), inches (in), feet (ft), yards (yd), miles (mi), and scientific units like light years and astronomical units. Type natural phrases like "5 feet 3 inches in cm" or "convert 10 km to miles" and the smart parser handles it automatically.',
    popularPairs: [
      { from: 'Meter', to: 'Feet', desc: 'm → ft — standard construction & height conversion' },
      { from: 'Kilometer', to: 'Miles', desc: 'km → mi — road distance & travel planning' },
      { from: 'Inches', to: 'Centimeter', desc: 'in → cm — screen sizes & clothing dimensions' },
      { from: 'Feet', to: 'Meters', desc: 'ft → m — real estate & architecture' },
      { from: 'Centimeter', to: 'Inches', desc: 'cm → in — product dimensions & body measurements' },
    ],
    useCases: ['Construction & architecture (ft↔m)', 'Travel & navigation (km↔mi)', 'Clothing & body measurements (in↔cm)', 'Scientific research (nm, μm, ly)', 'Real estate & property (ft↔m, ac↔ha)'],
    formula: 'Multiply by the conversion factor. For example: 1 meter = 3.28084 feet, 1 kilometer = 0.621371 miles.',
    faq: [
      { q: 'How do I convert meters to feet?', a: 'Multiply the length in meters by 3.28084 to get feet. For example, 10 meters × 3.28084 = 32.81 feet.' },
      { q: 'How many inches in a centimeter?', a: 'One centimeter equals 0.393701 inches. To convert cm to inches, multiply by 0.393701.' },
    ],
  },
  mass: {
    title: 'Weight & Mass Converter — Kilograms, Pounds, Ounces, Tons & More',
    metaDesc: 'Free online weight converter. Convert between kilograms, pounds, ounces, grams, metric tons, stone, and 15+ mass units. Perfect for cooking, shipping, fitness.',
    h1: 'Mass & Weight Conversion',
    intro: 'Convert between mass and weight units with precision. Supports metric units (kilogram, gram, milligram, metric ton), imperial units (pound, ounce, stone, US ton), and scientific units (atomic mass unit, electron volt). Whether you are tracking fitness goals, calculating shipping weights, or doing chemistry homework, the mass converter handles it all with up to 12 decimal places of precision.',
    popularPairs: [
      { from: 'Kilogram', to: 'Pounds', desc: 'kg → lb — fitness & body weight tracking' },
      { from: 'Pounds', to: 'Kilogram', desc: 'lb → kg — international shipping & travel' },
      { from: 'Ounces', to: 'Grams', desc: 'oz → g — cooking & baking recipes' },
      { from: 'Stone', to: 'Kilogram', desc: 'st → kg — UK body weight to metric' },
      { from: 'Metric Ton', to: 'US Ton', desc: 't → ton — industrial & freight' },
    ],
    useCases: ['Fitness & body weight (kg↔lb)', 'Cooking & recipes (oz↔g, lb↔g)', 'Shipping & logistics (kg↔lb, t↔ton)', 'Science & chemistry (amu, g)', 'Jewelry & precious metals (oz↔g)'],
    formula: '1 kilogram = 2.20462 pounds. 1 pound = 453.592 grams. 1 stone = 6.35029 kilograms.',
    faq: [
      { q: 'How many pounds in a kilogram?', a: 'One kilogram equals 2.20462 pounds. Multiply kg by 2.20462 to get pounds.' },
      { q: 'How do I convert ounces to grams?', a: 'Multiply ounces by 28.3495 to get grams. For example, 8 oz × 28.3495 = 226.8 grams.' },
    ],
  },
  temperature: {
    title: 'Temperature Converter — Celsius, Fahrenheit, Kelvin & 5 Scales',
    metaDesc: 'Free online temperature converter. Convert between Celsius, Fahrenheit, Kelvin, Rankine, and Réaumur. Includes formula explanations and real-world reference points.',
    h1: 'Temperature Conversion',
    intro: 'Convert between five temperature scales: Celsius (°C), Fahrenheit (°F), Kelvin (K), Rankine (°R), and Réaumur (°Re). The temperature converter uses precise formulas for each scale conversion and includes real-world reference points like freezing point (0°C / 32°F), boiling point (100°C / 212°F), and absolute zero (0 K / -273.15°C).',
    popularPairs: [
      { from: 'Celsius', to: 'Fahrenheit', desc: '°C → °F — weather & daily temperature' },
      { from: 'Fahrenheit', to: 'Celsius', desc: '°F → °C — international travel' },
      { from: 'Celsius', to: 'Kelvin', desc: '°C → K — scientific & chemistry calculations' },
      { from: 'Kelvin', to: 'Celsius', desc: 'K → °C — physics & engineering' },
      { from: 'Fahrenheit', to: 'Kelvin', desc: '°F → K — advanced science' },
    ],
    useCases: ['Weather & climate (°C↔°F)', 'Cooking & baking (°C↔°F)', 'Science & chemistry (K↔°C)', 'Engineering & physics (K↔°R)', 'HVAC & refrigeration'],
    formula: '°F = (°C × 9/5) + 32. K = °C + 273.15. °C = (°F − 32) × 5/9.',
    faq: [
      { q: 'How do I convert Celsius to Fahrenheit?', a: 'Multiply Celsius by 9/5 (1.8) then add 32. For example, 25°C × 1.8 + 32 = 77°F.' },
      { q: 'What is absolute zero in Celsius?', a: 'Absolute zero is 0 Kelvin, which equals -273.15°C or -459.67°F.' },
    ],
  },
  currency: {
    title: 'Currency Converter — Live Exchange Rates for 40+ World Currencies',
    metaDesc: 'Free live currency converter with real-time exchange rates. Convert USD, EUR, GBP, JPY, and 40+ world currencies. Auto-updates every 60 seconds.',
    h1: 'Currency Conversion',
    intro: 'Convert between 40+ world currencies with live exchange rates. The currency converter fetches real-time rates from reliable financial APIs and auto-updates every 60 seconds. Supports major currencies including USD, EUR, GBP, JPY, CAD, AUD, CHF, CNY, INR, and many more. Historical rate charts help you track trends over time.',
    popularPairs: [
      { from: 'USD', to: 'EUR', desc: 'USD → EUR — most traded forex pair' },
      { from: 'EUR', to: 'USD', desc: 'EUR → USD — international transactions' },
      { from: 'GBP', to: 'USD', desc: 'GBP → USD — GBP/USD cable rate' },
      { from: 'USD', to: 'JPY', desc: 'USD → JPY — Asian market conversion' },
      { from: 'USD', to: 'INR', desc: 'USD → INR — remittance & travel' },
    ],
    useCases: ['Travel & vacation budgeting', 'International business & remittance', 'E-commerce & cross-border shopping', 'Forex trading & analysis', 'Investment & portfolio management'],
    faq: [
      { q: 'How often are currency rates updated?', a: 'Exchange rates are fetched in real-time from financial APIs and refresh every 60 seconds while you are on the page.' },
      { q: 'Does the currency converter work offline?', a: 'Cached rates are available offline. The converter saves the last fetched rates so you can still convert even without internet.' },
    ],
  },
  crypto: {
    title: 'Crypto Converter — Bitcoin, Ethereum, Solana & Top Cryptocurrencies',
    metaDesc: 'Free live cryptocurrency converter. Real-time prices for Bitcoin, Ethereum, Solana, XRP, Dogecoin, and 50+ cryptocurrencies via CoinGecko.',
    h1: 'Cryptocurrency Conversion',
    intro: 'Convert between major cryptocurrencies and fiat currencies with live prices from CoinGecko. Track Bitcoin (BTC), Ethereum (ETH), Solana (SOL), XRP, Dogecoin (DOGE), Cardano (ADA), and 50+ altcoins. Prices update automatically every 60 seconds. The built-in sparkline chart shows price trends for each cryptocurrency.',
    popularPairs: [
      { from: 'Bitcoin', to: 'USD', desc: 'BTC → USD — leading crypto pair' },
      { from: 'Ethereum', to: 'USD', desc: 'ETH → USD — smart contract platform' },
      { from: 'Solana', to: 'USD', desc: 'SOL → USD — high-performance blockchain' },
      { from: 'XRP', to: 'USD', desc: 'XRP → USD — cross-border payments' },
      { from: 'Dogecoin', to: 'USD', desc: 'DOGE → USD — meme coin tracker' },
    ],
    useCases: ['Crypto trading & investment tracking', 'Portfolio valuation (BTC↔USD)', 'Crypto-to-crypto conversions', 'Real-time price monitoring', 'Tax calculation & reporting'],
    faq: [
      { q: 'Where do crypto prices come from?', a: 'Prices are sourced from CoinGecko API, which aggregates data from hundreds of cryptocurrency exchanges worldwide.' },
      { q: 'How often do crypto prices update?', a: 'Crypto prices refresh every 60 seconds, giving you near-real-time market data.' },
    ],
  },
  area: {
    title: 'Area Converter — Square Meters, Acres, Hectares, Square Feet & More',
    metaDesc: 'Free online area converter. Convert between square meters, square feet, acres, hectares, square kilometers, and 12+ area units. Perfect for real estate & land.',
    h1: 'Area Conversion',
    intro: 'Convert between area units for real estate, construction, agriculture, and science. Supports square meters (m²), square feet (ft²), square kilometers (km²), acres (ac), hectares (ha), square inches (in²), square yards (yd²), square miles (mi²), and scientific units like barns.',
    popularPairs: [
      { from: 'Square Meters', to: 'Square Feet', desc: 'm² → ft² — real estate & property listings' },
      { from: 'Acres', to: 'Hectares', desc: 'ac → ha — farmland & land measurement' },
      { from: 'Square Feet', to: 'Square Meters', desc: 'ft² → m² — international property comparison' },
      { from: 'Hectares', to: 'Acres', desc: 'ha → ac — agricultural land' },
      { from: 'Square Kilometers', to: 'Square Miles', desc: 'km² → mi² — country & region areas' },
    ],
    useCases: ['Real estate & property (m²↔ft²)', 'Agriculture & land (ac↔ha)', 'Construction & flooring (ft²↔m²)', 'Geography & mapping (km²↔mi²)', 'Science (barn, mm²)'],
    formula: '1 square meter = 10.7639 square feet. 1 acre = 0.404686 hectares. 1 hectare = 107,639 square feet.',
    faq: [
      { q: 'How many square feet in a square meter?', a: 'One square meter equals 10.7639 square feet. Multiply m² by 10.7639 to get ft².' },
      { q: 'How many acres in a hectare?', a: 'One hectare equals 2.47105 acres. Multiply hectares by 2.47105 to get acres.' },
    ],
  },
  volume: {
    title: 'Volume Converter — Liters, Gallons, Cubic Meters, Quarts & More',
    metaDesc: 'Free online volume converter. Convert between liters, gallons, quarts, pints, cubic meters, milliliters, and 15+ volume units. For cooking, shipping, science.',
    h1: 'Volume Conversion',
    intro: 'Convert between volume and capacity units for cooking, shipping, science, and industry. Supports metric units (milliliter, liter, cubic meter), US customary units (gallon, quart, pint, cup, fluid ounce), imperial units, and scientific units.',
    popularPairs: [
      { from: 'Liters', to: 'Gallons', desc: 'L → gal — fuel economy & liquid measurement' },
      { from: 'Gallons', to: 'Liters', desc: 'gal → L — international volume comparison' },
      { from: 'Milliliters', to: 'Fluid Ounces', desc: 'mL → fl oz — cooking & recipes' },
      { from: 'Cubic Meters', to: 'Cubic Feet', desc: 'm³ → ft³ — shipping & storage' },
      { from: 'Quarts', to: 'Liters', desc: 'qt → L — kitchen & cooking' },
    ],
    useCases: ['Cooking & baking (mL↔fl oz, cup)', 'Fuel & automotive (L↔gal)', 'Shipping & storage (m³↔ft³)', 'Science & chemistry (mL↔L)', 'Aquariums & pools (L↔gal)'],
    formula: '1 liter = 0.264172 gallons. 1 gallon = 3.78541 liters. 1 cubic meter = 35.3147 cubic feet.',
    faq: [
      { q: 'How many liters in a gallon?', a: 'One US gallon equals 3.78541 liters. One UK gallon equals 4.54609 liters.' },
      { q: 'How do I convert milliliters to fluid ounces?', a: 'Divide milliliters by 29.5735 to get US fluid ounces. For example, 250 mL ÷ 29.5735 = 8.45 fl oz.' },
    ],
  },
  speed: {
    title: 'Speed Converter — mph, km/h, Knots, Mach & Speed Units',
    metaDesc: 'Free online speed converter. Convert between miles per hour, kilometers per hour, knots, meters per second, Mach number, and more. Perfect for travel & aviation.',
    h1: 'Speed Conversion',
    intro: 'Convert between speed units for travel, aviation, marine, and science. Supports kilometers per hour (km/h), miles per hour (mph), knots (kn), meters per second (m/s), feet per second (ft/s), Mach number, and speed of light.',
    popularPairs: [
      { from: 'km/h', to: 'mph', desc: 'km/h → mph — road speed limits & travel' },
      { from: 'mph', to: 'km/h', desc: 'mph → km/h — international driving' },
      { from: 'Knots', to: 'mph', desc: 'kn → mph — aviation & marine' },
      { from: 'm/s', to: 'km/h', desc: 'm/s → km/h — physics & sports' },
      { from: 'Mach', to: 'km/h', desc: 'Mach → km/h — aerospace & aviation' },
    ],
    useCases: ['Driving & road trips (km/h↔mph)', 'Aviation (kn↔mph)', 'Marine navigation (kn)', 'Physics calculations (m/s)', 'Sports analytics (m/s↔km/h)'],
    formula: '1 mph = 1.60934 km/h. 1 knot = 1.15078 mph = 1.852 km/h. Mach 1 ≈ 1,235 km/h at sea level.',
    faq: [
      { q: 'How do I convert km/h to mph?', a: 'Divide km/h by 1.60934 to get mph. For example, 100 km/h ÷ 1.60934 = 62.14 mph.' },
      { q: 'What is the difference between knots and mph?', a: 'One knot equals 1.15078 mph. Knots are used in aviation and marine contexts, while mph is used for road travel.' },
    ],
  },
  time: {
    title: 'Time Converter — Seconds, Minutes, Hours, Days & Time Units',
    metaDesc: 'Free online time converter. Convert between seconds, minutes, hours, days, weeks, months, years, and more. Perfect for project planning & scheduling.',
    h1: 'Time Conversion',
    intro: 'Convert between time units for project management, scheduling, science, and everyday use. Supports seconds, minutes, hours, days, weeks, months, years, decades, centuries, and milliseconds.',
    popularPairs: [
      { from: 'Hours', to: 'Minutes', desc: 'h → min — scheduling & planning' },
      { from: 'Days', to: 'Hours', desc: 'd → h — project timelines' },
      { from: 'Minutes', to: 'Seconds', desc: 'min → s — precise timing' },
      { from: 'Weeks', to: 'Days', desc: 'wk → d — work & travel planning' },
      { from: 'Years', to: 'Days', desc: 'yr → d — long-term planning' },
    ],
    useCases: ['Project management (h↔min)', 'Fitness & workouts (min↔s)', 'Travel planning (d↔h)', 'Scientific experiments (ms↔s)', 'Payroll & billing (h↔min)'],
    formula: '1 hour = 60 minutes = 3,600 seconds. 1 day = 24 hours. 1 year = 365.25 days (accounting for leap years).',
    faq: [
      { q: 'How many minutes in a day?', a: 'There are 1,440 minutes in a day (24 hours × 60 minutes).' },
      { q: 'How do I convert hours to seconds?', a: 'Multiply hours by 3,600. For example, 2 hours × 3,600 = 7,200 seconds.' },
    ],
  },
  energy: {
    title: 'Energy Converter — Joules, Calories, kWh, BTU & Energy Units',
    metaDesc: 'Free online energy converter. Convert between joules, calories, kilowatt-hours, BTUs, electronvolts, and more. Perfect for physics, nutrition, and engineering.',
    h1: 'Energy Conversion',
    intro: 'Convert between energy units for physics, nutrition, engineering, and everyday use. Supports joules (J), kilojoules (kJ), calories (cal), kilocalories (Cal/kcal), watt-hours (Wh), kilowatt-hours (kWh), BTUs, electronvolts (eV), and foot-pounds.',
    popularPairs: [
      { from: 'Joules', to: 'Calories', desc: 'J → cal — physics & nutrition' },
      { from: 'kWh', to: 'BTU', desc: 'kWh → BTU — HVAC & energy bills' },
      { from: 'Calories', to: 'Joules', desc: 'Cal → J — food energy conversion' },
      { from: 'eV', to: 'Joules', desc: 'eV → J — particle physics' },
      { from: 'BTU', to: 'kWh', desc: 'BTU → kWh — heating & cooling' },
    ],
    useCases: ['Nutrition & diet tracking (Cal↔kJ)', 'Physics calculations (J↔eV)', 'Energy bills (kWh↔BTU)', 'Exercise & fitness (Cal↔J)', 'HVAC engineering (BTU↔kWh)'],
    formula: '1 calorie = 4.184 joules. 1 kWh = 3,412 BTU = 3.6 × 10⁶ J. 1 eV = 1.602 × 10⁻¹⁹ J.',
    faq: [
      { q: 'How many joules in a calorie?', a: 'One calorie equals 4.184 joules. A food Calorie (kcal) equals 4,184 joules.' },
      { q: 'How do I convert kWh to BTU?', a: 'Multiply kWh by 3,412 to get BTU. For example, 1 kWh × 3,412 = 3,412 BTU.' },
    ],
  },
  pressure: {
    title: 'Pressure Converter — PSI, Bar, Pascal, ATM & Pressure Units',
    metaDesc: 'Free online pressure converter. Convert between PSI, bar, pascals, atmospheres, torr, mmHg, and more. Perfect for engineering, diving, and meteorology.',
    h1: 'Pressure Conversion',
    intro: 'Convert between pressure units for engineering, meteorology, diving, and science. Supports pascals (Pa), kilopascals (kPa), megapascals (MPa), bar, PSI (pounds per square inch), atmospheres (atm), torr, millimeters of mercury (mmHg), and inches of mercury (inHg).',
    popularPairs: [
      { from: 'PSI', to: 'Bar', desc: 'psi → bar — tire pressure & automotive' },
      { from: 'Bar', to: 'PSI', desc: 'bar → psi — industrial pressure gauges' },
      { from: 'ATM', to: 'PSI', desc: 'atm → psi — scuba diving & depth' },
      { from: 'Pascals', to: 'PSI', desc: 'Pa → psi — scientific measurements' },
      { from: 'mmHg', to: 'ATM', desc: 'mmHg → atm — blood pressure & weather' },
    ],
    useCases: ['Tire pressure (PSI↔bar)', 'Scuba diving (atm↔psi)', 'Weather forecasting (hPa↔inHg)', 'HVAC & refrigeration (PSI↔bar)', 'Blood pressure (mmHg)'],
    formula: '1 bar = 14.5038 PSI = 100,000 Pa. 1 atm = 14.696 PSI = 101,325 Pa. 1 mmHg = 133.322 Pa.',
    faq: [
      { q: 'How do I convert PSI to bar?', a: 'Divide PSI by 14.5038 to get bar. For example, 36 PSI ÷ 14.5038 = 2.48 bar.' },
      { q: 'What is standard atmospheric pressure?', a: 'Standard atmospheric pressure is 1 atm = 14.696 PSI = 101.325 kPa = 29.92 inHg.' },
    ],
  },
  power: {
    title: 'Power Converter — Watts, Horsepower, BTU/h & Power Units',
    metaDesc: 'Free online power converter. Convert between watts, horsepower, kilowatts, BTUs per hour, and more. For engineering, automotive, and energy calculations.',
    h1: 'Power Conversion',
    intro: 'Convert between power units for engineering, automotive, energy, and science. Supports watts (W), kilowatts (kW), megawatts (MW), horsepower (hp), BTUs per hour (BTU/h), foot-pounds per minute, and calories per second.',
    popularPairs: [
      { from: 'Horsepower', to: 'Kilowatts', desc: 'hp → kW — engine power & automotive' },
      { from: 'Kilowatts', to: 'Horsepower', desc: 'kW → hp — international specs' },
      { from: 'Watts', to: 'BTU/h', desc: 'W → BTU/h — heating & cooling' },
      { from: 'MW', to: 'kW', desc: 'MW → kW — power plant output' },
      { from: 'Horsepower', to: 'Watts', desc: 'hp → W — mechanical power' },
    ],
    useCases: ['Automotive engine specs (hp↔kW)', 'Electrical appliances (W↔kW)', 'HVAC systems (BTU/h↔W)', 'Industrial machinery (MW↔kW)', 'Fitness equipment (W↔hp)'],
    formula: '1 horsepower = 745.7 watts = 0.7457 kW. 1 kW = 1.341 horsepower. 1 W = 3.412 BTU/h.',
    faq: [
      { q: 'How many kilowatts in one horsepower?', a: 'One horsepower equals 0.7457 kilowatts. To convert hp to kW, multiply by 0.7457.' },
      { q: 'How do I convert watts to BTU/h?', a: 'Multiply watts by 3.412 to get BTU per hour. For example, 1,000 W × 3.412 = 3,412 BTU/h.' },
    ],
  },
  force: {
    title: 'Force Converter — Newtons, Pound-Force, Dynes & Force Units',
    metaDesc: 'Free online force converter. Convert between newtons, pound-force, dynes, kilogram-force, and more. For physics and engineering calculations.',
    h1: 'Force Conversion',
    intro: 'Convert between force units for physics, engineering, and mechanics. Supports newtons (N), kilonewtons (kN), pound-force (lbf), dynes (dyn), kilogram-force (kgf), and ounce-force (ozf).',
    popularPairs: [
      { from: 'Newtons', to: 'Pound-Force', desc: 'N → lbf — physics & engineering' },
      { from: 'Pound-Force', to: 'Newtons', desc: 'lbf → N — mechanical systems' },
      { from: 'kN', to: 'lbf', desc: 'kN → lbf — structural engineering' },
      { from: 'Dynes', to: 'Newtons', desc: 'dyn → N — scientific calculations' },
      { from: 'kgf', to: 'N', desc: 'kgf → N — metric force conversions' },
    ],
    useCases: ['Structural engineering (kN↔lbf)', 'Physics experiments (N↔dyn)', 'Mechanical systems (N↔lbf)', 'Material testing (N↔kgf)', 'Aerospace engineering (kN↔lbf)'],
    formula: '1 newton = 0.224809 pound-force. 1 N = 100,000 dynes. 1 kgf = 9.80665 N.',
    faq: [
      { q: 'How many newtons in a pound-force?', a: 'One pound-force equals 4.44822 newtons. To convert lbf to N, multiply by 4.44822.' },
      { q: 'What is the difference between mass and force?', a: 'Mass (kg, lb) measures the amount of matter. Force (N, lbf) measures the push or pull. Weight is a force — mass × gravity.' },
    ],
  },
  data: {
    title: 'Data Storage Converter — Bytes, KB, MB, GB, TB & Digital Units',
    metaDesc: 'Free online data storage converter. Convert between bytes, kilobytes, megabytes, gigabytes, terabytes, and more. Perfect for IT & storage planning.',
    h1: 'Data Storage Conversion',
    intro: 'Convert between digital storage units for IT, software development, and data management. Supports bits, bytes, kilobytes (KB), megabytes (MB), gigabytes (GB), terabytes (TB), petabytes (PB), and both binary (KiB, MiB) and decimal (KB, MB) standards.',
    popularPairs: [
      { from: 'MB', to: 'GB', desc: 'MB → GB — storage capacity & file sizes' },
      { from: 'GB', to: 'MB', desc: 'GB → MB — memory & disk space' },
      { from: 'GB', to: 'TB', desc: 'GB → TB — large storage planning' },
      { from: 'KB', to: 'MB', desc: 'KB → MB — document & image sizes' },
      { from: 'Bits', to: 'Bytes', desc: 'b → B — networking & data transfer' },
    ],
    useCases: ['Storage capacity planning (GB↔TB)', 'File size management (MB↔GB)', 'Network bandwidth (bits↔bytes)', 'Cloud storage (GB↔TB)', 'Programming & development (KiB↔MiB)'],
    formula: '1 byte = 8 bits. 1 KB = 1,024 bytes. 1 MB = 1,024 KB. 1 GB = 1,024 MB. 1 TB = 1,024 GB.',
    faq: [
      { q: 'How many MB in a GB?', a: 'There are 1,024 MB in 1 GB (binary). For decimal (hard drive) notation, 1 GB = 1,000 MB.' },
      { q: 'What is the difference between a bit and a byte?', a: 'A bit is the smallest digital unit (0 or 1). A byte is 8 bits. Internet speeds are usually in bits (Mbps), while file sizes are in bytes (MB).' },
    ],
  },
  fuel: {
    title: 'Fuel Economy Converter — MPG, km/L, L/100km & Fuel Units',
    metaDesc: 'Free online fuel economy converter. Convert between miles per gallon, kilometers per liter, liters per 100km, and more. For automotive & fuel efficiency.',
    h1: 'Fuel Economy Conversion',
    intro: 'Convert between fuel economy units for automotive, fleet management, and travel planning. Supports miles per gallon US (mpg US), miles per gallon UK (mpg UK), kilometers per liter (km/L), and liters per 100 kilometers (L/100km).',
    popularPairs: [
      { from: 'MPG (US)', to: 'L/100km', desc: 'mpg → L/100km — fuel efficiency comparison' },
      { from: 'L/100km', to: 'MPG (US)', desc: 'L/100km → mpg — international vehicle specs' },
      { from: 'km/L', to: 'MPG (US)', desc: 'km/L → mpg — metric to imperial fuel economy' },
      { from: 'MPG (UK)', to: 'MPG (US)', desc: 'UK mpg → US mpg — UK vs US gallon difference' },
      { from: 'L/100km', to: 'km/L', desc: 'L/100km → km/L — common metric comparison' },
    ],
    useCases: ['Vehicle comparison (mpg↔L/100km)', 'Trip fuel planning (km/L↔L/100km)', 'Fleet management (mpg↔L/100km)', 'International car imports', 'Environmental impact calculation'],
    formula: 'L/100km = 235.215 / mpg (US). L/100km = 282.481 / mpg (UK). 1 km/L = 2.35215 mpg (US).',
    faq: [
      { q: 'How do I convert MPG to L/100km?', a: 'Divide 235.215 by your MPG value. For example, 30 MPG → 235.215 ÷ 30 = 7.84 L/100km.' },
      { q: 'What is the difference between US and UK gallons?', a: 'A US gallon is 3.785 liters, while a UK (imperial) gallon is 4.546 liters. This affects MPG calculations by about 20%.' },
    ],
  },
  angle: {
    title: 'Angle Converter — Degrees, Radians, Gradians & Angle Units',
    metaDesc: 'Free online angle converter. Convert between degrees, radians, gradians, minutes of arc, seconds of arc, and more. For math, navigation & engineering.',
    h1: 'Angle Conversion',
    intro: 'Convert between angle units for mathematics, navigation, engineering, and astronomy. Supports degrees (°), radians (rad), gradians (gon), arcminutes (′), arcseconds (″), and milliradians (mrad).',
    popularPairs: [
      { from: 'Degrees', to: 'Radians', desc: '° → rad — trigonometry & calculus' },
      { from: 'Radians', to: 'Degrees', desc: 'rad → ° — practical geometry' },
      { from: 'Degrees', to: 'Gradians', desc: '° → gon — surveying & land measurement' },
      { from: 'Arcminutes', to: 'Degrees', desc: "′ → ° — astronomy & navigation" },
      { from: 'Radians', to: 'mrad', desc: 'rad → mrad — precision targeting' },
    ],
    useCases: ['Trigonometry (°↔rad)', 'Navigation (°↔′↔″)', 'Surveying (gon↔°)', 'Astronomy (′↔″↔rad)', 'Engineering (rad↔mrad)'],
    formula: 'π radians = 180°. 1 radian ≈ 57.2958°. 1° = 60 arcminutes = 3,600 arcseconds.',
    faq: [
      { q: 'How do I convert degrees to radians?', a: 'Multiply degrees by π/180. For example, 180° × π/180 = π radians, 90° × π/180 = π/2 radians.' },
      { q: 'What is a gradian?', a: 'A gradian (gon) divides a right angle into 100 parts. 100 gradians = 90°, 400 gradians = 360°. Used in surveying and some European engineering.' },
    ],
  },
  frequency: {
    title: 'Frequency Converter — Hertz, kHz, MHz, GHz & Frequency Units',
    metaDesc: 'Free online frequency converter. Convert between hertz, kilohertz, megahertz, gigahertz, and more. For electronics, radio, and physics.',
    h1: 'Frequency Conversion',
    intro: 'Convert between frequency units for electronics, telecommunications, radio, and physics. Supports hertz (Hz), kilohertz (kHz), megahertz (MHz), gigahertz (GHz), terahertz (THz), rotations per minute (RPM), and beats per minute (BPM).',
    popularPairs: [
      { from: 'MHz', to: 'GHz', desc: 'MHz → GHz — CPU clock speeds & radio frequencies' },
      { from: 'GHz', to: 'MHz', desc: 'GHz → MHz — processor specifications' },
      { from: 'kHz', to: 'MHz', desc: 'kHz → MHz — AM radio & audio frequencies' },
      { from: 'Hz', to: 'kHz', desc: 'Hz → kHz — sound & audio processing' },
      { from: 'RPM', to: 'Hz', desc: 'RPM → Hz — motor speeds & machinery' },
    ],
    useCases: ['Electronics (Hz↔MHz↔GHz)', 'Radio & telecommunications (kHz↔MHz)', 'Audio processing (Hz↔kHz)', 'CPU & hardware specs (MHz↔GHz)', 'Motor & machinery (RPM↔Hz)'],
    formula: '1 kHz = 1,000 Hz. 1 MHz = 1,000 kHz = 1,000,000 Hz. 1 GHz = 1,000 MHz. 1 RPM = 1/60 Hz.',
    faq: [
      { q: 'How do I convert MHz to GHz?', a: 'Divide MHz by 1,000 to get GHz. For example, 2,400 MHz ÷ 1,000 = 2.4 GHz.' },
      { q: 'What is the difference between Hz and RPM?', a: 'Hz measures cycles per second, while RPM measures rotations per minute. 1 Hz = 60 RPM. To convert RPM to Hz, divide by 60.' },
    ],
  },
}
